#!/usr/bin/env python3
"""
Run ONNX inference from prepared NTU sample npy files.

Inputs:
- *_model_input.npy generated by prepare_ntu60_input_samples.py
  expected shape: (1, 1, 2, 64, 25, 3) or (1, Nc, M, T, V, C)

Outputs:
- prediction summary json with top-k scores per sample

Example:
python deployment/onnx/run_onnx_from_samples.py \
  --onnx deployment/artifacts/sem_sparse_ntu60_xview_joint.onnx \
  --samples-dir deployment/artifacts/ntu60_input_samples \
  --label-map tools/data/label_map/nturgbd_120.txt \
  --topk 5
"""

import argparse
import glob
import json
import os
from typing import List, Sequence, Tuple

import numpy as np


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Run ONNX from prepared sample npy files")
    parser.add_argument("--onnx", required=True, help="Path to onnx model")
    parser.add_argument("--samples-dir", required=True, help="Directory containing *_model_input.npy files")
    parser.add_argument(
        "--pattern",
        default="*_model_input.npy",
        help="Glob pattern in samples-dir",
    )
    parser.add_argument("--label-map", default=None, help="Optional label map txt")
    parser.add_argument(
        "--samples-summary",
        default=None,
        help="Optional summary json from sample preparation (default: <samples-dir>/summary.json)",
    )
    parser.add_argument("--topk", type=int, default=5, help="Top-k predictions")
    parser.add_argument(
        "--ort-provider",
        default="cpu",
        choices=["cpu", "cuda"],
        help="Execution provider for ONNX Runtime",
    )
    parser.add_argument(
        "--batch-files",
        type=int,
        default=16,
        help="Number of sample files processed per ONNX call",
    )
    parser.add_argument(
        "--output-json",
        default=None,
        help="Output json path, default: <samples-dir>/predictions.json",
    )
    return parser.parse_args()


def load_label_map(path: str) -> List[str]:
    labels: List[str] = []
    with open(path, "r", encoding="utf-8") as file:
        for line in file:
            text = line.strip()
            if text:
                labels.append(text)
    return labels


def create_session(onnx_path: str, ort_provider: str):
    try:
        import onnxruntime as ort
    except ImportError as exc:
        raise ImportError("onnxruntime is required. Install with: pip install onnxruntime") from exc

    available = ort.get_available_providers()
    if ort_provider == "cuda":
        if "CUDAExecutionProvider" in available:
            providers = ["CUDAExecutionProvider", "CPUExecutionProvider"]
        else:
            print("[Warn] CUDAExecutionProvider unavailable, fallback to CPUExecutionProvider.")
            providers = ["CPUExecutionProvider"]
    else:
        providers = ["CPUExecutionProvider"]

    session = ort.InferenceSession(onnx_path, providers=providers)
    return session


def load_model_input(path: str) -> np.ndarray:
    arr = np.load(path).astype(np.float32)
    if arr.ndim == 5:
        arr = arr[None, ...]
    if arr.ndim != 6:
        raise ValueError(f"Expected input with ndim=6, got shape={arr.shape}, file={path}")
    return arr


def topk_indices(scores: np.ndarray, k: int) -> Tuple[np.ndarray, np.ndarray]:
    k = max(1, min(k, scores.shape[1]))
    idx = np.argpartition(-scores, kth=k - 1, axis=1)[:, :k]
    row = np.arange(scores.shape[0])[:, None]
    val = scores[row, idx]
    order = np.argsort(-val, axis=1)
    idx = np.take_along_axis(idx, order, axis=1)
    val = np.take_along_axis(val, order, axis=1)
    return idx, val


def infer_batch(session, batch_input: np.ndarray) -> np.ndarray:
    input_name = session.get_inputs()[0].name
    output_name = session.get_outputs()[0].name
    outputs = session.run([output_name], {input_name: batch_input})
    scores = outputs[0]
    if scores.ndim != 2:
        raise RuntimeError(f"Expected output ndim=2, got shape={scores.shape}")
    return scores.astype(np.float32)


def chunk_list(items: Sequence[str], chunk_size: int) -> List[List[str]]:
    result: List[List[str]] = []
    for start in range(0, len(items), chunk_size):
        result.append(list(items[start : start + chunk_size]))
    return result


def infer_gt_from_sidecar(sample_path: str) -> int:
    base_name = os.path.basename(sample_path)
    if base_name.endswith("_model_input.npy"):
        prefix = base_name[: -len("_model_input.npy")]
        sidecar = os.path.join(os.path.dirname(sample_path), f"{prefix}.json")
        if os.path.isfile(sidecar):
            with open(sidecar, "r", encoding="utf-8") as file:
                payload = json.load(file)
            if isinstance(payload, dict) and "label" in payload:
                return int(payload["label"])
    return -1


def load_gt_labels_map(summary_json: str) -> dict:
    with open(summary_json, "r", encoding="utf-8") as file:
        data = json.load(file)
    mapping = {}
    samples = data.get("samples", []) if isinstance(data, dict) else []
    for item in samples:
        if not isinstance(item, dict):
            continue
        label = item.get("label", None)
        model_input_npy = item.get("model_input_npy", None)
        if label is None or model_input_npy is None:
            continue
        mapping[os.path.basename(str(model_input_npy))] = int(label)
    return mapping


def main() -> None:
    args = parse_args()
    output_json = args.output_json or os.path.join(args.samples_dir, "predictions.json")

    pattern = os.path.join(args.samples_dir, args.pattern)
    sample_paths = sorted(glob.glob(pattern))
    if len(sample_paths) == 0:
        raise FileNotFoundError(f"No files matched: {pattern}")

    summary_json = args.samples_summary or os.path.join(args.samples_dir, "summary.json")
    gt_map = {}
    if os.path.isfile(summary_json):
        gt_map = load_gt_labels_map(summary_json)
        print(f"[Info] Loaded GT labels from summary: {summary_json} ({len(gt_map)} items)")
    else:
        print("[Warn] summary.json not found, will try per-sample sidecar json for labels.")

    label_map = load_label_map(args.label_map) if args.label_map else None
    session = create_session(args.onnx, args.ort_provider)
    providers = session.get_providers()
    print(f"[Info] ONNX providers: {providers}")

    results = []
    eval_total = 0
    eval_correct = 0
    for group in chunk_list(sample_paths, max(1, args.batch_files)):
        arrays = [load_model_input(path) for path in group]
        batch_input = np.concatenate(arrays, axis=0)
        scores = infer_batch(session, batch_input)
        idx, val = topk_indices(scores, args.topk)

        for i, path in enumerate(group):
            top1 = int(idx[i, 0])
            base_name = os.path.basename(path)
            gt_label = gt_map.get(base_name, -1)
            if gt_label < 0:
                gt_label = infer_gt_from_sidecar(path)
            is_correct = (gt_label >= 0 and gt_label == top1)
            if gt_label >= 0:
                eval_total += 1
                if is_correct:
                    eval_correct += 1
            item = {
                "file": path,
                "pred_label": top1,
                "pred_name": (
                    label_map[top1] if (label_map is not None and top1 < len(label_map)) else str(top1)
                ),
                "gt_label": int(gt_label),
                "gt_name": (
                    label_map[gt_label]
                    if (gt_label >= 0 and label_map is not None and gt_label < len(label_map))
                    else (str(gt_label) if gt_label >= 0 else "")
                ),
                "is_top1_correct": bool(is_correct),
                "score": float(val[i, 0]),
                "topk": [
                    {
                        "label": int(idx[i, j]),
                        "name": (
                            label_map[int(idx[i, j])]
                            if (label_map is not None and int(idx[i, j]) < len(label_map))
                            else str(int(idx[i, j]))
                        ),
                        "score": float(val[i, j]),
                    }
                    for j in range(idx.shape[1])
                ],
                "model_input_shape": list(arrays[i].shape),
            }
            results.append(item)
            if gt_label >= 0:
                print(
                    f"[Pred] {base_name} -> top1={item['pred_label']} ({item['pred_name']}), "
                    f"gt={gt_label}, correct={bool(is_correct)}, score={item['score']:.6f}"
                )
            else:
                print(
                    f"[Pred] {base_name} -> top1={item['pred_label']} "
                    f"({item['pred_name']}), score={item['score']:.6f}"
                )

    top1_acc = float(eval_correct / eval_total) if eval_total > 0 else None
    if top1_acc is not None:
        print(f"[Eval] top1_acc={top1_acc:.4f} ({eval_correct}/{eval_total})")
    else:
        print("[Eval] top1_acc unavailable: no ground-truth labels found.")

    summary = {
        "onnx": args.onnx,
        "providers": providers,
        "num_samples": len(results),
        "topk": args.topk,
        "eval": {
            "num_with_gt": int(eval_total),
            "top1_correct": int(eval_correct),
            "top1_acc": top1_acc,
        },
        "results": results,
    }
    with open(output_json, "w", encoding="utf-8") as file:
        json.dump(summary, file, indent=2, ensure_ascii=False)
    print(f"[Done] Saved predictions: {output_json}")


if __name__ == "__main__":
    main()
